services:
  portfolio:
    image: ghcr.io/alandeveloper/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`alandeveloper.com.br`) || Host(`www.alandeveloper.com.br`)"
      - "traefik.http.routers.portfolio.entrypoints=web"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
